Authentication interceptor
DBCG/cqf-ruler pull request #528
Opened 2022-06-03 00:14 UTC by mdnazmulkarim

2022-06-03 18:22 UTC, JPercival requested changes

2022-06-03 21:21 UTC, mdnazmulkarim commented on plugin/cr/src/main/java/org/opencds/cqf/ruler/cr/CrConfig.java
> +	public AuthenticationInterceptor authenticationInterceptor() { return new AuthenticationInterceptor(); }
Done.

2022-06-06 16:01 UTC, JPercival requested changes

2022-06-06 16:01 UTC, JPercival commented on plugin/security/src/test/java/org/opencds/cqf/ruler/security/interceptor/AuthenticatorInterceptorIT.java
> +	public void testMeasureEvaluateAuth() throws Exception {
Can we simplify this test to simply be posting/reading data? Adding Measure eval to the test complicates it and could lead to false failures.

2022-06-06 16:21 UTC, mdnazmulkarim commented on plugin/cds-hooks/src/test/java/org/opencds/cqf/ruler/plugin/cdshooks/dstu3/CdsHooksServletIT.java
> +				"hapi.fhir.fhir_version=dstu3", "hapi.fhir.security.security_configuration.enabled=false"
ye it is disabled by default, but for some reason, the test suite in cds hooks was not picking automatically.

2022-06-06 18:45 UTC, JPercival approved these changes

2022-06-06 22:06 UTC, rob-reynolds requested changes

2022-06-06 22:06 UTC, rob-reynolds commented on plugin/security/src/main/java/org/opencds/cqf/ruler/security/interceptor/AuthenticationInterceptor.java
> +			 * Here we test for a hardcoded username & password. This is
I think we should remove this comment.

2022-06-06 22:12 UTC, mdnazmulkarim commented on plugin/security/src/main/java/org/opencds/cqf/ruler/security/interceptor/AuthenticationInterceptor.java
> +			 * Here we test for a hardcoded username & password. This is
Done!

2022-06-06 22:33 UTC, rob-reynolds approved these changes
Looks good.

2022-06-06 23:53 UTC, merged